### ISSUE TITLE
dplyr's all_equal has no tolerance for floating point errors

### ISSUE THREAD

**Issue by chvp** [dodona-edu/judge-r#67]
The existing code tries to work around this using `signif` but that doesn't always work (e.g. 1.173e-16 and 0 are not considered equal).

**Comment by driesbenoit** [comment]
We have encountered the same problem with the `all()` function in base R (btw, you probably mean .1.173e-16 and 0?). For example, changing the order of variables in linear regression leads to tiny differences in estimates due to floating point errors when inverting the design matrix. We solve it using the round function (but the number of requested digits is dependent on the exercise/values), see e.g.:
````R
  testcase('Is the value of fit.1 correct?', {
    testEqual("", function(env) { env$fit.1$coefficients }, fit.1$coefficients,
              comparator = function(generated_val, expected_val, ...) {
                test <- all(round(expected_val, 8) %in% round(generated_val, 8))
                return(test)
              })
  })
````
